[build-system]
requires = ["setuptools>=46.1.0", "setuptools_scm[toml]>=5"]
build-backend = "setuptools.build_meta"

[project]
name = "MacroStat"
description = "Tools for the statistical analysis and treatment of macroeconomic simulation models, with a focus on Agent-based and Stock-Flow Consistent Models"
readme = "README.rst"
license = "MIT"
requires-python = ">=3.11"
authors = [
    { name = "Karl Naumann-Woleske", email = "karl.naumann@icloud.com" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
]
dynamic = ["version"]
dependencies = [
    "dash",
    "dash-cytoscape",
    "matplotlib",
    "networkx",
    "numpy",
    "pandas",
    "scipy",
    "torch",
    "tqdm",
]

[project.optional-dependencies]
io = [
    "fastparquet",
    "openpyxl",
]
testing = [
    "pytest",
    "pytest-cov",
]
docs = [
    "myst-nb>=1.4.0",
    "pydata-sphinx-theme",
    "sphinx-design>=0.7.0",
    "sphinxcontrib-bibtex>=2.6.5",
]

[project.urls]
Source = "https://github.com/KarlNaumann/MacroStat/"

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests"]

[tool.setuptools_scm]
version_scheme = "no-guess-dev"

[dependency-groups]
dev = [
    "ipykernel",
    "jupyterlab",
    "jupytext>=1.19.1",
    "pytest>=9.0",
    "pytest-cov>=7.0.0",
]
